Add `headertitle` option
Nuckal777/ba-latex-template pull request #23
Opened 2024-09-05 23:19 UTC by Paulchen5

Add 2 options to the `\documentclass` command
+ `header`: controls whether a header line is shown or not
+ `headertitle`: controls the content of the headerline
> If only `header` is provided the title of the document will be used in the header. When `headertitle` is used but not specified a note message will be shown. In case `headertitle` is specified with a value this value will be shown in the header.

2024-09-06 09:03 UTC, Nuckal777 requested changes
Thanks. 👍 Please take a look at my remarks and add the new options to the documentation. I cannot judge the spacing changes though.

2024-09-06 09:03 UTC, Nuckal777 commented on baarticle.cls
> +\DeclareOptionX[BA]{headertitle}[no header title provided for headertitle option | it's recommended to use a maximum lentgth of 80 characters to prevent this overflow]{\def\@baclsheadertitle{#1}}
Could we use `\@batitletitle` as default as previously? The comment about length could be moved to the documentation.

2024-09-06 09:03 UTC, Nuckal777 commented on baarticle.cls
> +\DeclareOptionX[BA]{header}[useheader]{\toggletrue{baclsheader}}
I'd like to avoid changing the current defaults. Could the meaning be flipped? E.g. having a `noheader` option.

2024-09-06 09:03 UTC, Nuckal777 commented on baarticle.cls
> +    \expandafter\ifx\csname @baclsheadertitle\endcsname\relax
I think this can be replaced with `\ifdefvoid` from the `etoolbox` package.

Additionally, `\@baclsheadertitle` has a default value of `no header title provided for headertitle...`. The default could be `\@batitletitle`, which would avoid this check entirely.

2024-09-07 08:52 UTC, Paulchen5 commented on baarticle.cls
> +\DeclareOptionX[BA]{headertitle}[no header title provided for headertitle option | it's recommended to use a maximum lentgth of 80 characters to prevent this overflow]{\def\@baclsheadertitle{#1}}
Is it possible to use the value here? Because it's defined later.

2024-09-10 07:39 UTC, Nuckal777 commented on baarticle.cls
> +\DeclareOptionX[BA]{headertitle}[no header title provided for headertitle option | it's recommended to use a maximum lentgth of 80 characters to prevent this overflow]{\def\@baclsheadertitle{#1}}
I don't know for sure, but it's worth a try. Macros aren't necessarily evaluated immediately. [Here](https://tex.stackexchange.com/a/519) is an outline about macro expansion, that I could quickly dig up.

2024-09-10 07:41 UTC, Nuckal777 commented
Looks good. Would you mind to add the two new options to [this list](https://github.com/ba-dresden/ba-latex-template/blob/rewrite/docs/usage/simple.md?plain=1#L40) in the docs?

2024-09-10 10:32 UTC, Paulchen5 commented
I've added the two options to the docs 👍

2024-09-13 09:27 UTC, Paulchen5 reviewed
I swapped the spacing so you don't take too much space if you use the noheader option.

2024-09-13 11:38 UTC, Nuckal777 commented on baarticle.cls
> +\DeclareOptionX[BA]{headertitle}[no header title provided for headertitle option | it's recommended to use a maximum lentgth of 80 characters to prevent this overflow]{\def\@baclsheadertitle{#1}}
Doesn't work. 🥲

2024-09-13 13:27 UTC, Nuckal777 approved these changes

2024-09-13 13:28 UTC, merged

2024-09-13 18:52 UTC, Paulchen5 commented on baarticle.cls
> +\DeclareOptionX[BA]{headertitle}[no header title provided for headertitle option | it's recommended to use a maximum lentgth of 80 characters to prevent this overflow]{\def\@baclsheadertitle{#1}}
I didn't see your suggestion😅